 http://localhost:3000/cursos

###
GET http://localhost:3000/cursos/3

###

POST http://localhost:3000/cursos HTTP/1.1
content-type: application/json

  {
    "nome": "PORTINARI"
  }

###
PUT http://localhost:3000/cursos/5 HTTP/1.1
content-type: application/json
  {
    "nome": "PORTINARI"
  }
###
DELETE http://localhost:3000/cursos/7 HTTP/1.1
###

POST http://localhost:3000/files HTTP/1.1
content-type: application/json

 [ {
    "originalname": "junior",
    "filename": "1594379088014-239732968-Max Payne 3 - Invadindo a favela!.mp4"
  },
  {
    "originalname": "my",
    "filename": "aloha"
  }]


GET http://localhost:3000/files?_page=1&_limit=1
